qsort:qsorts
qsorts:c_qsort.cc
	g++ -g c_qsort.cc -o c_qsort.out

sort:main
main:stl_sort.cc
	g++ -g stl_sort.cc -o stl_sort.out

stable:stable
stable:stl_stable_sort.cc
	g++ -g stl_stable_sort.cc -o stl_stable_sort.out

partial:partialsorts
partialsorts:stl_partial_sort.cc
	g++ -g stl_partial_sort.cc -o stl_partial_sort.out

nth:nths
nths:stl_nth_sort.cc
	g++ -g stl_nth_sort.cc -o stl_nth_sort.out
